---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-app-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image:  <some-elastic-container-registry-end-point>/nginx-app:latest
        ports:
        - containerPort: 80

